#!/usr/bin/env python3
"""Check emitted debug resource closure and disabled elision without simulation."""
import argparse
import hashlib
import json
from pathlib import Path
from run import ROOT, RTL

def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument("directory",type=Path)
    parser.add_argument("--mode",choices=("off","stub","external"),required=True)
    args=parser.parse_args();directory=args.directory.resolve()
    top=directory/"JtagDebugReservation.sv";text=top.read_text()
    listed=[line.strip() for line in (directory/"filelist.f").read_text().splitlines() if line.strip()]
    expected={"JtagDebugReservation.sv"} | ({RTL.name} if args.mode!="off" else set())
    if set(listed)!=expected or len(listed)!=len(expected):
        raise RuntimeError(f"Incomplete/duplicate export filelist: {listed}; expected {sorted(expected)}")
    for name in listed:
        if not (directory/name).is_file():raise RuntimeError(f"Missing exported source {name}")
    if args.mode=="off":
        if "ValenceJtag" in text or "always" in text or " reg " in text:
            raise RuntimeError("Disabled export retains debug cells or storage")
    else:
        exported=(directory/RTL.name).read_text()
        # firtool adds its provenance line and may drop the final newline.
        if exported.startswith("// Generated by CIRCT firtool-"):
            exported=exported.split("\n",1)[1]
        if exported.rstrip("\n")!=RTL.read_text().rstrip("\n"):
            raise RuntimeError("Stale/changed exported resource")
        if ".EXTERNAL_DMI("+str(int(args.mode=="external"))+")" not in text:
            raise RuntimeError("Wrong endpoint selection")
    print(json.dumps({"status":"passed","mode":args.mode,"files":[
        {"name":name,"sha256":hashlib.sha256((directory/name).read_bytes()).hexdigest()}
        for name in sorted(expected)],"scope":"export closure and structural checks, not behavioral proof"},indent=2))

if __name__=="__main__":main()
