version = 3.10.3
runner.dialect = scala213
maxColumn = 120

align.preset = more
indent.main = 4
indent.callSite = 4
fileOverride {
  "glob:**/legacy/tests/scala/core/LSUSpec.scala/**" {
     runner.dialect = scala3
  }
  "glob:**/legacy/tests/scala/core/InstrFetchSpec.scala/**" {
     runner.dialect = scala3
  }
  "glob:**/legacy/tests/scala/device/TileLinkDeviceTestUtils.scala/**" {
     runner.dialect = scala3
  }
  "glob:**/legacy/tests/scala/bus/TLCoherenceHubSpec.scala/**" {
     runner.dialect = scala3
  }
  "glob:**/legacy/tests/scala/memory/L1CacheSpec.scala/**" {
     runner.dialect = scala3
  }
  "glob:**/legacy/tests/scala/bus/TLSystemXbarSpec.scala/**" {
     runner.dialect = scala3
  }
  "glob:**/legacy/tests/scala/core/FrontendQueueSpec.scala/**" {
     runner.dialect = scala3
  }
  "glob:**/riscv-tests/benchmarks/mm/gen.scala/**" {
     runner.dialect = scala3
  }
  "glob:**/legacy/tests/scala/device/CLINTSpec.scala/**" {
     runner.dialect = scala3
  }
  "glob:**/riscv-tests/benchmarks/spmv/spmv_gendata.scala/**" {
     runner.dialect = scala3
  }
  "glob:**/legacy/tests/scala/core/CSRFileSpec.scala/**" {
     runner.dialect = scala3
  }
  "glob:**/legacy/tests/scala/system/IonSoCSpec.scala/**" {
     runner.dialect = scala3
  }
  "glob:**/legacy/tests/scala/core/DcachePtwArbiterSpec.scala/**" {
     runner.dialect = scala3
  }
  "glob:**/build.mill/**" {
     runner.dialect = scala3
  }
  "glob:**/legacy/tests/scala/device/TLDeviceSpec.scala/**" {
     runner.dialect = scala3
  }
  "glob:**/legacy/tests/scala/core/SatpWriteBarrierSpec.scala/**" {
     runner.dialect = scala3
  }
  "glob:**/legacy/tests/scala/debug/DebugModuleSpec.scala/**" {
     runner.dialect = scala3
  }
  "glob:**/legacy/tests/scala/core/LoadUseScoreboardSpec.scala/**" {
     runner.dialect = scala3
  }
  "glob:**/legacy/tests/scala/core/BranchPredictorSpec.scala/**" {
     runner.dialect = scala3
  }
  "glob:**/legacy/tests/scala/core/ALUSpec.scala/**" {
     runner.dialect = scala3
  }
  "glob:**/legacy/tests/scala/bus/TLXbarSpec.scala/**" {
     runner.dialect = scala3
  }
  "glob:**/legacy/tests/scala/device/PLICSpec.scala/**" {
     runner.dialect = scala3
  }
  "glob:**/legacy/tests/scala/core/InstrDecodeSpec.scala/**" {
     runner.dialect = scala3
  }
  "glob:**/legacy/tests/scala/core/Sv39Spec.scala/**" {
     runner.dialect = scala3
  }
  "glob:**/legacy/tests/scala/debug/JtagTapSpec.scala/**" {
     runner.dialect = scala3
  }
  "glob:**/legacy/tests/scala/core/StoreBufferSpec.scala/**" {
     runner.dialect = scala3
  }
  "glob:**/legacy/tests/scala/device/UartSpec.scala/**" {
     runner.dialect = scala3
  }
}
