package soc.core.ooo

import chisel3._

/** Passive qualification wires. They do not grant ownership or drive protocol. */
class CheckedStorePrefetchObservation(mshrBits: Int) extends Bundle {
    val candidate = Bool()
    val candidateStore = Bool()
    val allocated = Bool()
    val allocatedStore = Bool()
    val useful = Bool()
    val usefulStore = Bool()
    val allocatedAddress = UInt(64.W)
    val allocatedSlot = UInt(mshrBits.W)
    val demandAlloc = Bool()
    val demandAllocSlot = UInt(mshrBits.W)
    val demandAllocAddress = UInt(64.W)
    val mshrLiveMask = UInt(4.W)
    val mshrPrefetchMask = UInt(4.W)
    val mshrStoreMask = UInt(4.W)
    val refill = Bool()
    val refillSlot = UInt(mshrBits.W)
    val refillAddress = UInt(64.W)
    val refillPrefetch = Bool()
    val refillError = Bool()
    val wbCapture = Bool()
    val wbCaptureSlot = UInt(2.W)
    val wbCaptureMshr = UInt(mshrBits.W)
    val wbCaptureAddress = UInt(64.W)
    val wbCaptureDirty = Bool()
    val wbCaptureDirect = Bool()
    val wbCaptureFromMiss = Bool()
    val wbCapturePrefetch = Bool()
    val wbLiveMask = UInt(4.W)
    val wbSentMask = UInt(4.W)
    val wbPrefetchMask = UInt(4.W)
    val wbAddress0 = UInt(64.W)
    val wbAddress1 = UInt(64.W)
    val wbMshr0 = UInt(mshrBits.W)
    val wbMshr1 = UInt(mshrBits.W)
    val acquireResponsePending = Bool()
    val queuedEvictWanted = Bool()
    val responseFull = Bool()
    val cValid = Bool()
    val cReady = Bool()
    val cOpcode = UInt(3.W)
    val cParam = UInt(3.W)
    val cSize = UInt(3.W)
    val cData = UInt(64.W)
    val dData = UInt(64.W)
    val dDenied = Bool()
    val dCorrupt = Bool()

}
