package soc.core.ooo

import chisel3._

/** Passive qualification wires. They do not grant ownership or drive protocol. */
class CheckedStorePrefetchObservation(mshrBits: Int) extends Bundle {
    val candidate = Bool()
    val candidateStore = Bool()
    val allocated = Bool()
    val allocatedStore = Bool()
    val useful = Bool()
    val usefulStore = Bool()
    val allocatedAddress = UInt(64.W)
    val allocatedSlot = UInt(mshrBits.W)
    // Candidate-set snapshots are passive and valid-guarded. Cache resident
    // indices are distinct from the allocated MSHR slot and support up to 512 lines.
    val pendingCandidateValid = Bool()
    val pendingCandidateStore = Bool()
    val pendingCandidateAddress = UInt(64.W)
    val pendingCandidateSet = UInt(9.W)
    val candidateReplacementWay = Bool()
    val candidateWay0Valid = Bool()
    val candidateWay0Dirty = Bool()
    val candidateWay0Address = UInt(64.W)
    val candidateWay1Valid = Bool()
    val candidateWay1Dirty = Bool()
    val candidateWay1Address = UInt(64.W)
    val candidateVictimIndex = UInt(9.W)
    val candidateVictimWay = Bool()
    val candidateVictimValid = Bool()
    val candidateVictimDirty = Bool()
    val candidateVictimAddress = UInt(64.W)
    val allocatedIndex = UInt(9.W)
    val allocatedVictimValid = Bool()
    val allocatedVictimDirty = Bool()
    val allocatedVictimAddress = UInt(64.W)
    val demandAlloc = Bool()
    val demandAllocSlot = UInt(mshrBits.W)
    val demandAllocAddress = UInt(64.W)
    val mshrLiveMask = UInt(4.W)
    val mshrPrefetchMask = UInt(4.W)
    val mshrStoreMask = UInt(4.W)
    val refill = Bool()
    val refillSlot = UInt(mshrBits.W)
    val refillAddress = UInt(64.W)
    val refillPrefetch = Bool()
    val refillError = Bool()
    val refillIndex = UInt(9.W)
    val installValid = Bool()
    val installIndex = UInt(9.W)
    val installAddress = UInt(64.W)
    val installDirty = Bool()
    val wbCapture = Bool()
    val wbCaptureSlot = UInt(2.W)
    val wbCaptureMshr = UInt(mshrBits.W)
    val wbCaptureAddress = UInt(64.W)
    val wbCaptureIndex = UInt(9.W)
    val wbCaptureDirty = Bool()
    val wbCaptureDirect = Bool()
    val wbCaptureFromMiss = Bool()
    val wbCapturePrefetch = Bool()
    val wbLiveMask = UInt(4.W)
    val wbSentMask = UInt(4.W)
    val wbPrefetchMask = UInt(4.W)
    val wbAddress0 = UInt(64.W)
    val wbAddress1 = UInt(64.W)
    val wbMshr0 = UInt(mshrBits.W)
    val wbMshr1 = UInt(mshrBits.W)
    val acquireResponsePending = Bool()
    val queuedEvictWanted = Bool()
    val responseFull = Bool()
    val cValid = Bool()
    val cReady = Bool()
    val cOpcode = UInt(3.W)
    val cParam = UInt(3.W)
    val cSize = UInt(3.W)
    val cData = UInt(64.W)
    val dData = UInt(64.W)
    val dDenied = Bool()
    val dCorrupt = Bool()

}
