package soc.core.ooo

import chisel3._
import chisel3.util._
import soc.ip.dma.EthernetAxisWord

/** Native Vivado AXI Ethernet v7.2 generated by generate_ethernet_ip.tcl. */
class VivadoAxiEthernet extends BlackBox {
    override def desiredName: String = "axi_ethernet_0"
    val io = IO(new Bundle {
        val s_axi_lite_resetn = Input(Bool())
        val s_axi_lite_clk = Input(Clock())
        val axis_clk = Input(Clock())
        val gtx_clk = Input(Clock())
        val ref_clk = Input(Clock())
        val axi_txd_arstn = Input(Bool())
        val axi_txc_arstn = Input(Bool())
        val axi_rxd_arstn = Input(Bool())
        val axi_rxs_arstn = Input(Bool())
        val mac_irq = Output(Bool())
        val interrupt = Output(Bool())
        val phy_rst_n = Output(UInt(1.W))
        val s_axi_awaddr = Input(UInt(18.W))
        val s_axi_awvalid = Input(Bool())
        val s_axi_awready = Output(Bool())
        val s_axi_wdata = Input(UInt(32.W))
        val s_axi_wstrb = Input(UInt(4.W))
        val s_axi_wvalid = Input(Bool())
        val s_axi_wready = Output(Bool())
        val s_axi_bresp = Output(UInt(2.W))
        val s_axi_bvalid = Output(Bool())
        val s_axi_bready = Input(Bool())
        val s_axi_araddr = Input(UInt(18.W))
        val s_axi_arvalid = Input(Bool())
        val s_axi_arready = Output(Bool())
        val s_axi_rdata = Output(UInt(32.W))
        val s_axi_rresp = Output(UInt(2.W))
        val s_axi_rvalid = Output(Bool())
        val s_axi_rready = Input(Bool())
        val s_axis_txd_tdata = Input(UInt(32.W))
        val s_axis_txd_tkeep = Input(UInt(4.W))
        val s_axis_txd_tlast = Input(Bool())
        val s_axis_txd_tvalid = Input(Bool())
        val s_axis_txd_tready = Output(Bool())
        val s_axis_txc_tdata = Input(UInt(32.W))
        val s_axis_txc_tkeep = Input(UInt(4.W))
        val s_axis_txc_tlast = Input(Bool())
        val s_axis_txc_tvalid = Input(Bool())
        val s_axis_txc_tready = Output(Bool())
        val m_axis_rxd_tdata = Output(UInt(32.W))
        val m_axis_rxd_tkeep = Output(UInt(4.W))
        val m_axis_rxd_tlast = Output(Bool())
        val m_axis_rxd_tvalid = Output(Bool())
        val m_axis_rxd_tready = Input(Bool())
        val m_axis_rxs_tdata = Output(UInt(32.W))
        val m_axis_rxs_tkeep = Output(UInt(4.W))
        val m_axis_rxs_tlast = Output(Bool())
        val m_axis_rxs_tvalid = Output(Bool())
        val m_axis_rxs_tready = Input(Bool())
        val rgmii_rd = Input(UInt(4.W))
        val rgmii_rx_ctl = Input(Bool())
        val rgmii_rxc = Input(Clock())
        val rgmii_td = Output(UInt(4.W))
        val rgmii_tx_ctl = Output(Bool())
        val rgmii_txc = Output(Clock())
        val mdio_mdc = Output(Bool())
        val mdio_mdio_i = Input(Bool())
        val mdio_mdio_o = Output(Bool())
        val mdio_mdio_t = Output(Bool())
    })
}

/** Integration/synthesis boundary, NOT a board-ready top or Linux network device.
  * CPU clock/reset and DDR AXI remain external. Ethernet uses fixed 125 MHz
  * and a separate 333.333 MHz delay-reference clock (generated IP's actual
  * REFCLK_FREQUENCY). Four packet AXIS interfaces
  * are external by default; opt-in packetDma connects four stream CDC FIFOs to
  * the coherent, CPU-domain self-designed packet DMA. Never wire them across clocks directly.
  * MDIO is split i/o/t for the final board wrapper's IOBUF.
  */
class EthernetSocTop(isa: String = BoardSocConfig.isaProfile,
    timingProfile: String = "staged-ethernet", packetDma: Boolean = false) extends Module {
    val io = IO(new Bundle {
        val ethernetClock = Input(Clock())
        val ethernetRefClock = Input(Clock())
        val ddrReady = Input(Bool())
        val ddrAxi = new _root_.soc.ip.axi.Axi4MemoryPort(32, 4)
        val uartRx = Input(Bool())
        val uartTx = Output(Bool())
        val txData = if (!packetDma) Some(Flipped(Decoupled(new EthernetAxisWord))) else None
        val txControl = if (!packetDma) Some(Flipped(Decoupled(new EthernetAxisWord))) else None
        val rxData = if (!packetDma) Some(Decoupled(new EthernetAxisWord)) else None
        val rxStatus = if (!packetDma) Some(Decoupled(new EthernetAxisWord)) else None
        val rgmiiRd = Input(UInt(4.W))
        val rgmiiRxCtl = Input(Bool())
        val rgmiiRxc = Input(Clock())
        val rgmiiTd = Output(UInt(4.W))
        val rgmiiTxCtl = Output(Bool())
        val rgmiiTxc = Output(Clock())
        val phyResetn = Output(Bool())
        val mdc = Output(Bool())
        val mdioIn = Input(Bool())
        val mdioOut = Output(Bool())
        val mdioTristate = Output(Bool())
    })
    val soc = Module(new BoardSocTop(socClockHz = 100000000, externalDdr = true,
        timingProfile = timingProfile, uartBaud = 460800, dataCacheWays = 2,
        issueWidth = 2, isaProfile = isa, peripheralClockHz = 125000000, ethernetControl = true,
        ethernetDma = packetDma))
    soc.io.peripheralClock.get := io.ethernetClock
    soc.io.ddrReady.get := io.ddrReady
    io.ddrAxi <> soc.io.ddrAxi.get
    soc.io.uartRx := io.uartRx
    io.uartTx := soc.io.uartTx
    val mac = Module(new VivadoAxiEthernet)
    val active = !soc.io.ethernetReset.get
    mac.io.s_axi_lite_clk := io.ethernetClock
    mac.io.axis_clk := io.ethernetClock
    mac.io.gtx_clk := io.ethernetClock
    mac.io.ref_clk := io.ethernetRefClock
    mac.io.s_axi_lite_resetn := active
    mac.io.axi_txd_arstn := active
    mac.io.axi_txc_arstn := active
    mac.io.axi_rxd_arstn := active
    mac.io.axi_rxs_arstn := active
    val macIrqLevel = withClockAndReset(io.ethernetClock, soc.io.ethernetReset.get) {
        RegNext(mac.io.interrupt || mac.io.mac_irq, false.B)
    }
    soc.io.ethernetIrq.get := macIrqLevel
    val control = soc.io.ethernetAxi.get
    mac.io.s_axi_awaddr := control.aw.bits.addr(17, 0)
    mac.io.s_axi_awvalid := control.aw.valid
    control.aw.ready := mac.io.s_axi_awready
    mac.io.s_axi_wdata := control.w.bits.data
    mac.io.s_axi_wstrb := control.w.bits.strb
    mac.io.s_axi_wvalid := control.w.valid
    control.w.ready := mac.io.s_axi_wready
    control.b.bits := mac.io.s_axi_bresp
    control.b.valid := mac.io.s_axi_bvalid
    mac.io.s_axi_bready := control.b.ready
    mac.io.s_axi_araddr := control.ar.bits.addr(17, 0)
    mac.io.s_axi_arvalid := control.ar.valid
    control.ar.ready := mac.io.s_axi_arready
    control.r.bits.data := mac.io.s_axi_rdata
    control.r.bits.resp := mac.io.s_axi_rresp
    control.r.valid := mac.io.s_axi_rvalid
    mac.io.s_axi_rready := control.r.ready
    val txData = Wire(Decoupled(new EthernetAxisWord))
    val txControl = Wire(Decoupled(new EthernetAxisWord))
    val rxData = Wire(Decoupled(new EthernetAxisWord))
    val rxStatus = Wire(Decoupled(new EthernetAxisWord))
    if (packetDma) {
        // Reset both FIFO endpoints and DMA together. The Ethernet guard additionally
        // resets queued partial frames; no independent hot reset is supported.
        val commonReset = (reset.asBool || !io.ddrReady || soc.io.ethernetReset.get).asAsyncReset
        def crossing(source: DecoupledIO[EthernetAxisWord], destination: DecoupledIO[EthernetAxisWord],
            from: Clock, to: Clock): Unit = {
            val fifo = Module(new _root_.soc.ip.bus.StreamClockDomainFifo(16))
            fifo.sourceClock := from
            fifo.destinationClock := to
            fifo.commonReset := commonReset
            fifo.source.valid := source.valid
            fifo.source.bits.data := source.bits.data
            fifo.source.bits.keep := source.bits.keep
            fifo.source.bits.last := source.bits.last
            fifo.source.bits.user := false.B
            source.ready := fifo.source.ready
            destination.valid := fifo.destination.valid
            destination.bits.data := fifo.destination.bits.data(31, 0)
            destination.bits.keep := fifo.destination.bits.keep(3, 0)
            destination.bits.last := fifo.destination.bits.last
            fifo.destination.ready := destination.ready
        }
        crossing(soc.io.ethernetStreams.get.txData, txData, clock, io.ethernetClock)
        crossing(soc.io.ethernetStreams.get.txControl, txControl, clock, io.ethernetClock)
        crossing(rxData, soc.io.ethernetStreams.get.rxData, io.ethernetClock, clock)
        crossing(rxStatus, soc.io.ethernetStreams.get.rxStatus, io.ethernetClock, clock)
    } else {
        txData <> io.txData.get
        txControl <> io.txControl.get
        io.rxData.get <> rxData
        io.rxStatus.get <> rxStatus
    }
    mac.io.s_axis_txd_tdata := txData.bits.data
    mac.io.s_axis_txd_tkeep := txData.bits.keep
    mac.io.s_axis_txd_tlast := txData.bits.last
    mac.io.s_axis_txd_tvalid := txData.valid
    txData.ready := mac.io.s_axis_txd_tready
    mac.io.s_axis_txc_tdata := txControl.bits.data
    mac.io.s_axis_txc_tkeep := txControl.bits.keep
    mac.io.s_axis_txc_tlast := txControl.bits.last
    mac.io.s_axis_txc_tvalid := txControl.valid
    txControl.ready := mac.io.s_axis_txc_tready
    rxData.bits.data := mac.io.m_axis_rxd_tdata
    rxData.bits.keep := mac.io.m_axis_rxd_tkeep
    rxData.bits.last := mac.io.m_axis_rxd_tlast
    rxData.valid := mac.io.m_axis_rxd_tvalid
    mac.io.m_axis_rxd_tready := rxData.ready
    rxStatus.bits.data := mac.io.m_axis_rxs_tdata
    rxStatus.bits.keep := mac.io.m_axis_rxs_tkeep
    rxStatus.bits.last := mac.io.m_axis_rxs_tlast
    rxStatus.valid := mac.io.m_axis_rxs_tvalid
    mac.io.m_axis_rxs_tready := rxStatus.ready
    mac.io.rgmii_rd := io.rgmiiRd
    mac.io.rgmii_rx_ctl := io.rgmiiRxCtl
    mac.io.rgmii_rxc := io.rgmiiRxc
    io.rgmiiTd := mac.io.rgmii_td
    io.rgmiiTxCtl := mac.io.rgmii_tx_ctl
    io.rgmiiTxc := mac.io.rgmii_txc
    io.phyResetn := mac.io.phy_rst_n(0)
    io.mdc := mac.io.mdio_mdc
    mac.io.mdio_mdio_i := io.mdioIn
    io.mdioOut := mac.io.mdio_mdio_o
    io.mdioTristate := mac.io.mdio_mdio_t
}
